/**
 * Assembles a complete Terraform configuration from a compiled architecture.
 *
 * The output is a single `main.tf` plus a `terraform.tfvars.json`. One file
 * because the configuration is generated, never hand-edited: splitting it across
 * files would only make the diff a human reviews before approving harder to
 * read.
 *
 * The generated config is deterministic — same plan in, byte-identical config
 * out. That is what lets a plan be hashed, shown to an approver, and then proven
 * to be the same plan that ran.
 */
import { renderBlocks, type HclBlock } from './hcl';
import type { ProviderMapper, MapperContext, MappingResult } from '../providers/types';
import type { LogicalArchitecture } from '../types';

export interface GeneratedConfig {
  /** Contents of main.tf. */
  mainTf: string;
  /** Contents of terraform.tfvars.json. */
  tfvars: Record<string, unknown>;
  /** Terraform address per LAM node key, for joining plan output back to nodes. */
  addressByNode: Record<string, string>;
  /** LAM node key per Terraform address — the reverse lookup the engine needs. */
  nodeByAddress: Record<string, string>;
  /** Logical types the mapper could not build. Shown to the user. */
  unsupported: MappingResult['unsupported'];
  resourceCount: number;
}

export interface GenerateOptions {
  architecture: LogicalArchitecture;
  mapper: ProviderMapper;
  region: string;
  namePrefix: string;
}

export function generateTerraform(opts: GenerateOptions): GeneratedConfig {
  const { architecture, mapper, region, namePrefix } = opts;

  const ctx: MapperContext = {
    architecture,
    region,
    environment: architecture.metadata.environment,
    namePrefix,
  };

  // Sorted by node key so the same plan always produces the same file. An
  // approver comparing two plans should see only real differences.
  const nodes = [...architecture.nodes].sort((a, b) => a.key.localeCompare(b.key));
  const result = mapper.map(nodes, ctx);

  const variableBlocks: HclBlock[] = Object.entries(result.variables)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, spec]) => ({
      type: 'variable',
      labels: [name],
      body: {
        type: { __hclRef: true, expr: spec.type } as never,
        description: spec.description,
        sensitive: spec.sensitive || undefined,
      },
    }));

  const resourceBlocks = result.resources.flatMap((r) => r.blocks);

  // Outputs let the engine read back what was actually created, rather than
  // assuming the apply produced what the plan described.
  const outputBlocks: HclBlock[] = result.resources.map((r) => ({
    type: 'output',
    labels: [`${r.address.replace('.', '_')}_id`],
    body: {
      value: { __hclRef: true, expr: `${r.address}.id` } as never,
      description: `Identifier of ${r.nodeKey}`,
    },
  }));

  const header = [
    '# Generated by the CloudWise Infrastructure Deployment Agent.',
    '# Do not edit by hand: this file is regenerated from the approved plan,',
    '# and an edit here would mean the applied config is not the approved one.',
    `# Environment: ${architecture.metadata.environment}  Region: ${region}`,
    '',
  ].join('\n');

  const mainTf = [
    header,
    renderBlocks(result.preamble),
    renderBlocks(variableBlocks),
    renderBlocks(resourceBlocks),
    renderBlocks(outputBlocks),
  ]
    .filter((s) => s.trim().length > 0)
    .join('\n\n') + '\n';

  const addressByNode: Record<string, string> = {};
  const nodeByAddress: Record<string, string> = {};
  for (const r of result.resources) {
    addressByNode[r.nodeKey] = r.address;
    nodeByAddress[r.address] = r.nodeKey;
  }

  return {
    mainTf,
    tfvars: { region, name_prefix: namePrefix },
    addressByNode,
    nodeByAddress,
    unsupported: result.unsupported,
    resourceCount: resourceBlocks.length,
  };
}
