/**
 * The file set that goes into a deployment pull request.
 *
 * Four files, and each one answers a question the reviewer will otherwise ask:
 *
 *   main.tf                  what will be created
 *   terraform.tfvars.json    with what inputs
 *   README.md                what this is, what it costs, how to run it
 *   .github/workflows/...    who applies it, and with which credentials
 *
 * The workflow file is the part that changes the security model. With it, the
 * CUSTOMER'S pipeline runs `terraform apply` using the customer's own cloud
 * identity, and CloudWise never needs deploy credentials at all. That is a far
 * easier enterprise conversation than "give us a key that can create
 * infrastructure", and it is why emitting the pipeline is the default.
 *
 * Everything here is a pure function of the plan. No I/O, so the exact bytes
 * that will be committed can be asserted in a test.
 */
import type { GeneratedConfig } from '../terraform/generator';
import type { FileChange } from './types';

export interface DeploymentFilesInput {
  /** Directory inside the repo, e.g. "infrastructure". */
  basePath: string;
  /** Per-deployment directory name. Stable for the life of the deployment. */
  slug: string;
  planName: string;
  environment: string;
  region: string;
  provider: string;
  generated: GeneratedConfig;
  estimatedMonthlyCost: number | null;
  /** Human-readable state location, or null when state is local. */
  backendDescription: string | null;
  emitPipeline: boolean;
  /**
   * Set when the customer uses OIDC federation rather than stored keys. This is
   * the better path by a distance — no long-lived credential exists to leak —
   * so it is what the generated workflow uses when a role ARN is known.
   */
  awsRoleArn?: string | null;
}

const GENERATED_BANNER =
  '<!-- Generated by the CloudWise Infrastructure Deployment Agent. Edits here are overwritten when the plan is regenerated. -->';

export function buildDeploymentFiles(input: DeploymentFilesInput): FileChange[] {
  const dir = `${trimSlashes(input.basePath)}/${input.slug}`;

  const files: FileChange[] = [
    { path: `${dir}/main.tf`, content: input.generated.mainTf },
    {
      path: `${dir}/terraform.tfvars.json`,
      content: JSON.stringify(input.generated.tfvars, null, 2) + '\n',
    },
    { path: `${dir}/README.md`, content: readme(input, dir) },
  ];

  if (input.emitPipeline) {
    files.push({
      path: `.github/workflows/cloudwise-${input.slug}.yml`,
      content: workflow(input, dir),
    });
  }

  return files;
}

function trimSlashes(v: string): string {
  return v.replace(/^\/+|\/+$/g, '');
}

const money = (n: number | null): string =>
  n === null || !Number.isFinite(n) ? 'not estimated' : `$${n.toFixed(2)}/month`;

function readme(input: DeploymentFilesInput, dir: string): string {
  const unsupported = input.generated.unsupported ?? [];

  return [
    `# ${input.planName}`,
    '',
    GENERATED_BANNER,
    '',
    '| | |',
    '|---|---|',
    `| Environment | \`${input.environment}\` |`,
    `| Provider | \`${input.provider}\` |`,
    `| Region | \`${input.region}\` |`,
    `| Resources | ${input.generated.resourceCount} |`,
    `| Estimated cost | ${money(input.estimatedMonthlyCost)} |`,
    `| Terraform state | ${input.backendDescription ?? '**local — not durable**'} |`,
    '',
    '## What this is',
    '',
    'Terraform generated by the CloudWise infrastructure agent from a cost-estimated requirement.',
    'It has not been applied. Merging this pull request is what creates the infrastructure.',
    '',
    ...(input.backendDescription
      ? []
      : [
          '> **Warning**',
          '> No remote state backend is configured, so Terraform will keep state locally in the',
          '> runner. That state is lost when the job ends, which orphans anything this creates —',
          '> it will keep running and billing with nothing tracking it. Configure a state backend',
          '> in CloudWise before merging.',
          '',
        ]),
    ...(unsupported.length > 0
      ? [
          '## Not included',
          '',
          'The agent could not express these parts of the design in Terraform. They are **absent**',
          'from this configuration and need to be handled separately:',
          '',
          ...unsupported.map((u: any) => `- \`${u.nodeKey ?? u.type ?? 'unknown'}\` — ${u.reason ?? 'unsupported'}`),
          '',
        ]
      : []),
    '## Reviewing this',
    '',
    'Read `main.tf`. The agent applies exactly what is in it — nothing is added at apply time.',
    'Things worth checking before approving:',
    '',
    '- network exposure: security groups, public IPs, publicly accessible databases',
    '- encryption at rest on every storage and database resource',
    '- IAM: does any role grant more than the workload needs',
    '- instance sizes against the estimated cost above',
    '',
    '## Applying it',
    '',
    input.emitPipeline
      ? [
          'Merging runs the workflow in `.github/workflows/`, which applies this configuration with',
          'your own cloud credentials. CloudWise does not hold them and does not run the apply.',
        ].join('\n')
      : [
          'No pipeline was generated. Apply it yourself:',
          '',
          '```bash',
          `cd ${dir}`,
          'terraform init',
          'terraform plan -out=tfplan',
          'terraform apply tfplan',
          '```',
        ].join('\n'),
    '',
  ].join('\n');
}

/**
 * The GitHub Actions workflow.
 *
 * Two jobs on purpose. `plan` runs on the pull request and posts what would
 * change, so the reviewer sees the effect rather than only the source. `apply`
 * runs on the default branch after merge — gated on the event, so a fork's pull
 * request can never trigger an apply against the customer's account.
 */
function workflow(input: DeploymentFilesInput, dir: string): string {
  const usesOidc = Boolean(input.awsRoleArn);

  const credentialStep = usesOidc
    ? [
        '      - name: Configure AWS credentials (OIDC)',
        '        uses: aws-actions/configure-aws-credentials@v4',
        '        with:',
        `          role-to-assume: ${input.awsRoleArn}`,
        `          aws-region: ${input.region}`,
      ]
    : [
        '      # No federated role was configured, so this falls back to stored keys.',
        '      # Prefer OIDC: it removes the long-lived credential entirely.',
        '      - name: Configure AWS credentials',
        '        uses: aws-actions/configure-aws-credentials@v4',
        '        with:',
        '          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}',
        '          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}',
        `          aws-region: ${input.region}`,
      ];

  return [
    `# Generated by the CloudWise Infrastructure Deployment Agent for "${input.planName}".`,
    '#',
    '# plan  — runs on the pull request, reports what would change.',
    '# apply — runs only after merge to the default branch.',
    '#',
    usesOidc
      ? '# Credentials come from GitHub OIDC; no cloud secret is stored in this repository.'
      : '# Set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as repository secrets before merging.',
    '',
    `name: CloudWise · ${input.planName}`,
    '',
    'on:',
    '  pull_request:',
    '    paths:',
    `      - '${dir}/**'`,
    '  push:',
    '    branches: [ ${{ github.event.repository.default_branch }} ]',
    '    paths:',
    `      - '${dir}/**'`,
    '',
    '# Least privilege by default. id-token is what lets the runner federate',
    '# into the cloud account without a stored key.',
    'permissions:',
    '  contents: read',
    '  pull-requests: write',
    ...(usesOidc ? ['  id-token: write'] : []),
    '',
    '# One apply at a time. Two concurrent applies against one state file is the',
    '# fastest way to corrupt it beyond recovery.',
    'concurrency:',
    `  group: cloudwise-${input.slug}`,
    '  cancel-in-progress: false',
    '',
    'jobs:',
    '  plan:',
    "    if: github.event_name == 'pull_request'",
    '    runs-on: ubuntu-latest',
    '    defaults:',
    '      run:',
    `        working-directory: ${dir}`,
    '    steps:',
    '      - uses: actions/checkout@v4',
    ...credentialStep,
    '      - uses: hashicorp/setup-terraform@v3',
    '        with:',
    '          terraform_version: 1.9.8',
    '      - run: terraform init',
    '      - run: terraform validate',
    '      - name: Plan',
    '        id: plan',
    '        run: terraform plan -no-color -input=false',
    '',
    '  apply:',
    "    if: github.event_name == 'push'",
    '    runs-on: ubuntu-latest',
    '    defaults:',
    '      run:',
    `        working-directory: ${dir}`,
    '    steps:',
    '      - uses: actions/checkout@v4',
    ...credentialStep,
    '      - uses: hashicorp/setup-terraform@v3',
    '        with:',
    '          terraform_version: 1.9.8',
    '      - run: terraform init',
    '      # plan then apply the saved file, never a bare `apply`: a bare apply',
    '      # re-plans at run time, so what gets built is not what was reviewed.',
    '      - run: terraform plan -out=tfplan -input=false',
    '      - run: terraform apply -input=false -auto-approve tfplan',
    '',
  ].join('\n');
}

// ── Pull request body ─────────────────────────────────────────────────────────

export interface PullRequestBodyInput extends DeploymentFilesInput {
  requirements: string;
  /** Highest risk level across the plan's stages, from staging.ts. */
  riskLevel?: string;
  riskReasons?: string[];
  raisedBy: string | null;
}

/**
 * What the reviewer reads first.
 *
 * Leads with cost and blast radius rather than with a description of the
 * architecture. The reviewer is deciding whether to let this into their cloud
 * account; "12 resources, $430/month, creates an IAM role" is the information
 * that decision needs.
 */
export function buildPullRequestBody(input: PullRequestBodyInput): string {
  const unsupported = input.generated.unsupported ?? [];

  return [
    '## CloudWise deployment proposal',
    '',
    '| | |',
    '|---|---|',
    `| Resources | **${input.generated.resourceCount}** |`,
    `| Estimated cost | **${money(input.estimatedMonthlyCost)}** |`,
    `| Environment | \`${input.environment}\` |`,
    `| Region | \`${input.region}\` |`,
    `| Terraform state | ${input.backendDescription ?? '⚠️ **local — not durable**'} |`,
    ...(input.riskLevel ? [`| Highest risk | \`${input.riskLevel}\` |`] : []),
    ...(input.raisedBy ? [`| Requested by | ${input.raisedBy} |`] : []),
    '',
    '### Requirement this was generated from',
    '',
    '> ' + input.requirements.trim().split('\n').join('\n> '),
    '',
    ...(input.riskReasons && input.riskReasons.length > 0
      ? ['### Why this needs a careful read', '', ...input.riskReasons.map(r => `- ${r}`), '']
      : []),
    ...(unsupported.length > 0
      ? [
          '### ⚠️ Not included',
          '',
          'The agent could not express these in Terraform. They are absent from this change:',
          '',
          ...unsupported.map((u: any) => `- \`${u.nodeKey ?? u.type ?? 'unknown'}\` — ${u.reason ?? 'unsupported'}`),
          '',
        ]
      : []),
    ...(input.backendDescription
      ? []
      : [
          '### ⚠️ No remote state',
          '',
          'Terraform will keep state on the runner, and it is discarded when the job ends.',
          'Anything created here becomes untracked: it cannot be updated or destroyed by Terraform',
          'afterwards, and will keep billing. Configure a state backend in CloudWise before merging.',
          '',
        ]),
    '### Merging this',
    '',
    input.emitPipeline
      ? 'Merging triggers the generated workflow, which applies the configuration using this repository\'s own cloud credentials. CloudWise does not run the apply and does not hold those credentials.'
      : 'No pipeline was generated. Apply the configuration manually after merging — see the README in this change.',
    '',
    '---',
    '',
    '*Raised automatically by the CloudWise infrastructure agent. Comment on this pull request to request changes.*',
    '',
  ].join('\n');
}
